name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-actions-${{ env.RELEASE_VERSION }}
          retention-days: 1
          path: ${{ github.workspace }}/README.md

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-actions-${{ env.RELEASE_VERSION }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "etc/usr/artifacts/test-actions-${{ env.RELEASE_VERSION }}/*"
          body: "This is the release for tag ${{ env.RELEASE_VERSION}}"
          makeLatest: "true"